knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf
        options:    []
#    image:
#        enabled:    true
  #        binary: '%kernel.project_dir%/public/pdf'
#        options:    []
